version: '3.8'
services:

  todolist-db:
    image: postgres:10.7
    environment:
      - POSTGRES_USER=siva
      - POSTGRES_PASSWORD=secret
      - POSTGRES_DB=appdb
      - PGDATA=/data/postgres
    ports:
      - "5432:5432"
    restart: unless-stopped
