name: Master Branch CI

on:
  push:
    branches:
      - master
      - release
jobs:
  test:
    name: Unit & Integration Tests
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11

      - name: Cache Gradle packages
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: ${{ runner.os }}-gradle-

      - name: Build with Gradle
        run: ./gradlew clean build

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Package
          path: build/libs

  docker-publish:
    name: Build and Publish Docker Image
    needs: [test]
    runs-on: ubuntu-18.04
    env:
      DOCKER_IMAGE_NAME: ${{ secrets.DOCKER_USER }}/spring-boot-todolist
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 1.11
      - name: Login to DockerHub
        run: docker login -u ${{ secrets.DOCKER_USER }} -p ${{ secrets.DOCKER_PASS }}

      - name: Build Docker image
        run: ./gradlew bootBuildImage

      - name: Publish Docker image
        run: docker push $DOCKER_IMAGE_NAME
